core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("workflow_organizer.urls")),
    path('', include('theme_soft_design.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

workflow_organizer/urls.py
from django.urls import path

from .views import (
    index,
    TaskTypeListView,
    TaskTypeCreate,
    TaskTypeUpdate,
    TaskTypeDelete,
    PositionListView,
    PositionCreate,
    PositionUpdate,
    PositionDelete,
    ProjectDetailView,
    ProjectCreate,
    ProjectUpdate,
    ProjectDelete,
    TeamDetailView,
    WorkerDetailView,
    WorkerCreate,
    WorkerUpdate,
    WorkerDelete,
    TaskDetailView,
    TaskCreate,
    TaskUpdate,
    TaskDelete,
    TeamCreate,
    TeamUpdate,
    TeamDelete,
    UsersListView,
    toggle_assign_to_task,
    toggle_assign_to_project,
    toggle_add_to_team,
    task_panel,
    dashboard,
    project_tracking_panel,
)

urlpatterns = [
    path(
        "task-types/",
        TaskTypeListView.as_view(),
        name="task-type-list"
    ),
    path(
        "task-types/create/",
        TaskTypeCreate.as_view(),
        name="task-type-create"
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdate.as_view(),
        name="task-type-update"
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDelete.as_view(),
        name="task-type-delete"
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "positions/create/",
        PositionCreate.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdate.as_view(),
        name="position-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDelete.as_view(),
        name="position-delete"
    ),
    path(
        "teams/<int:pk>/",
        TeamDetailView.as_view(),
        name="team-detail"
    ),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "accounts/register/",
        WorkerCreate.as_view(),
        name="worker-create"
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdate.as_view(),
        name="worker-update"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDelete.as_view(),
        name="worker-delete"
    ),
    path(
        "task_panel/",
        task_panel,
        name="task-panel"
    ),
    path(
        "project_tracking_panel/",
        project_tracking_panel,
        name="project-tracking-panel"
    ),
    path(
        "tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "tasks/create/",
        TaskCreate.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdate.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDelete.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/toggle-assign/",
        toggle_assign_to_task,
        name="toggle-task-assign",
    ),
    path(
        "dashboard/",
        dashboard,
        name="dashboard"
    ),
    path(
        "project_tracking_panel/",
        project_tracking_panel,
        name="project_tracking_panel"
    ),
    path(
        "projects/<int:pk>/",
        ProjectDetailView.as_view(),
        name="project-detail"
    ),
    path(
        "users_list/",
        UsersListView.as_view(),
        name="users-list"
    ),
    path(
        "projects/<int:pk>/",
        ProjectDetailView.as_view(),
        name="project-detail"
    ),
    path(
        "projects/<int:pk>/toggle-assign/",
        toggle_assign_to_project,
        name="toggle-project-assign",
    ),
    path(
        "projects/create/",
        ProjectCreate.as_view(),
        name="project-create"
        ),
    path(
        "projects/<int:pk>/update",
        ProjectUpdate.as_view(),
        name="project-update"
        ),
    path(
        "projects/<int:pk>/delete",
        ProjectDelete.as_view(),
        name="project-delete"
        ),
    path(
        "teams/create/",
        TeamCreate.as_view(),
        name="team-create"
    ),
    path(
        "teams/<int:pk>/update/",
        TeamUpdate.as_view(),
        name="team-update"
    ),
    path("teams/<int:pk>/delete",
         TeamDelete.as_view(),
         name="team-delete"),

    path(
        "teams/<int:pk>/toggle-add/",
        toggle_add_to_team,
        name="toggle-team-add",
    ),
    path("", index, name="index"),
]

app_name = "workflow_organizer"

workflow_organizer/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet, Q, Count
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic


from .forms import (
    TaskForm,
    TaskTypeForm,
    TaskTypeSearchForm,
    PositionForm,
    PositionSearchForm,
    WorkerCreateForm,
    ProjectForm,
    TeamForm,
)
from .models import Tag, Task, TaskType, Position, Worker, Project, Team


def index(request):
    """View function for the home page of the site."""

    context = {
        "num_teams": Team.objects.count(),
        "num_projects": Project.objects.count(),
        "num_workers": get_user_model().objects.count()
    }

    return render(request, "workflow_organizer/index.html", context=context)


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    context_object_name = "task_type_list"
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskTypeSearchForm(initial={
            "name": name
        })
        return context

    def get_queryset(self):
        queryset = TaskType.objects.all()

        form = TaskTypeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TaskTypeCreate(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    form_class = TaskTypeForm
    success_url = reverse_lazy("workflow_organizer:task-type-list")


class TaskTypeUpdate(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    form_class = TaskTypeForm
    success_url = reverse_lazy("workflow_organizer:task-type-list")


class TaskTypeDelete(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("workflow_organizer:task-type-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = PositionSearchForm(initial={
            "name": name
        })
        return context

    def get_queryset(self) -> QuerySet:
        queryset = Position.objects.all()
        form = PositionSearchForm(self.request.GET)

        if form.is_valid():
            queryset = Position.objects.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class PositionCreate(LoginRequiredMixin, generic.CreateView):
    model = Position
    form_class = PositionForm
    success_url = reverse_lazy("workflow_organizer:position-list")


class PositionUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Position
    form_class = PositionForm
    success_url = reverse_lazy("workflow_organizer:position-list")


class PositionDelete(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("workflow_organizer:position-list")


class TeamDetailView(LoginRequiredMixin, generic.DetailView):
    model = Team


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = get_user_model().objects.select_related("position")

class WorkerCreate(generic.CreateView):
    model = Worker
    form_class = WorkerCreateForm
    success_url = reverse_lazy("workflow_organizer:index")


class WorkerUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerCreateForm

    def get_success_url(self):
        return reverse_lazy("workflow_organizer:worker-detail", kwargs={
            "pk": self.kwargs["pk"]
        })


class WorkerDelete(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("workflow_organizer:index")


@login_required
def toggle_assign_to_task(request, pk):
    assignee = get_user_model().objects.get(id=request.user.id)
    if (
        Task.objects.get(id=pk) in assignee.tasks.all()
    ):
        assignee.tasks.remove(pk)
    else:
        assignee.tasks.add(pk)
    return HttpResponseRedirect(reverse_lazy(
        "workflow_organizer:task-detail", args=[pk]
    ))

    return render(request, "workflow_organizer/task_panel.html", context)


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    queryset = Task.objects.select_related(
        "task_type"
    ).prefetch_related("assignees")


class TaskCreate(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("workflow_organizer:task-panel")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class TaskUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm

    def get_success_url(self):
        return reverse_lazy("workflow_organizer:task-detail", kwargs={
            "pk": self.kwargs["pk"]
        })

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class TaskDelete(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("workflow_organizer:index")


def dashboard(request):

    teams = Team.objects.annotate(projects_count=Count("projects"))

    context = {
        "projects": Project.objects.select_related("team"),
        "teams": teams
    }

    return render(request, "workflow_organizer/dashboard.html", context)


def task_panel(request):
    tag = request.GET.get("tag") or ""
    tags = Tag.objects.filter(name__contains=tag) if tag else Tag.objects.all()
    queue_tasks = Task.objects.filter(status='QUEUE', tags__name__contains=tag).distinct()
    underway_tasks = Task.objects.filter(status='UNDERWAY', tags__name__contains=tag).distinct()
    completed_tasks = Task.objects.filter(status='COMPLETED', tags__name__contains=tag).distinct()
    context = {
        'queue_tasks': queue_tasks,
        'underway_tasks': underway_tasks,
        'completed_tasks': completed_tasks,
        'tags': tags,
    }
    return render(request, 'workflow_organizer/task_panel.html', context)


def project_tracking_panel(request):
    total_projects = Project.objects.all()
    completed_projects = Project.objects.filter(is_completed=True).count()
    projects = Project.objects.all()

    progress_list = []
    for project in projects:
        if project.is_completed:
            progress_list.append(100)
        elif project.progress is not None:
            progress_list.append(project.progress)
        else:
            progress_list.append(0)

    time_constraints = Project.objects.values_list('time_constraints', flat=True)
    funds = Project.objects.values_list('budget', flat=True)

    context = {
        'total_projects': total_projects,
        'completed_projects': completed_projects,
        'progress': progress_list,
        'time_constraints': time_constraints,
        'funds': funds,
    }

    return render(request, 'workflow_organizer/project_tracking_panel.html', context)


class UsersListView(generic.ListView):
    model = Worker
    context_object_name = 'users'
    ordering = ['-rating_point']
    paginate_by = 10  # If you want pagination, set the number of items per page here

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        top_users = context['object_list'][:3]
        other_users = context['object_list'][3:]
        context['top_users'] = top_users
        context['other_users'] = other_users
        return context


class ProjectDetailView(generic.DetailView):
    model = Project

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["completed_projects"] = Project.objects.filter(is_completed=True).count()
        return context


class ProjectCreate(LoginRequiredMixin, generic.CreateView):
    model = Project
    form_class = ProjectForm
    success_url = reverse_lazy("workflow_organizer:dashboard")


class ProjectUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Project
    form_class = ProjectForm

    def get_success_url(self):
        return reverse_lazy("workflow_organizer:project-detail", kwargs={
            "pk": self.kwargs["pk"]
        })


class ProjectDelete(LoginRequiredMixin, generic.DeleteView):
    model = Project
    success_url = reverse_lazy("workflow_organizer:dashboard")


@login_required
def toggle_assign_to_project(request, pk):
    team = Team.objects.get(id=request.user.team.id)
    project = Project.objects.get(id=pk)
    if (
        project in team.projects.all()
    ):
        team.projects.remove(project)
    else:
        team.projects.add(project)
    return HttpResponseRedirect(reverse_lazy(
        "workflow_organizer:project-detail", args=[pk]
    ))


class TeamCreate(LoginRequiredMixin, generic.CreateView):
    model = Team
    form_class = TeamForm
    success_url = reverse_lazy("workflow_organizer:dashboard")


class TeamUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Team
    form_class = TeamForm
    success_url = reverse_lazy("workflow_organizer:dashboard")



templates/workflow_organizer/community_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/workflow_organizer/facility_form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/workflow_organizer/new_project.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/workflow_organizer/position_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block title %} {{ object|yesno:"Update,Create" }} Position {% endblock %}

{% block content %}

{% include "includes/sidebar.html" %}

  <div class="row">
    <header>
      <div class="page-header min-height-300">
        <span class="mask bg-gradient-success opacity-4"></span>
      </div>
    </header>

    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
      <section class="py-sm-7 py-5 position-relative">
        <div class="container">
          <div class="row">
            <div class="col-12 mx-auto">
              <div class="row py-5">
                <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mx-auto mb-4">
                  <div class="d-flex justify-content-between align-items-center">
                    <h2 class="mb-4">{{ object|yesno:"Update,Create" }} Position</h2>
                  </div>
                  <br><br>
                  <form action="" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" value="Submit" class="btn bg-gradient-success mx-auto">
                    <a class="btn bg-gradient-danger mx-4" href="{% url 'workflow_organizer:position-list' %}">Cancel</a>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>

{% endblock content %}

templates/workflow_organizer/position_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} Task Board {% endblock %}

{% block content %}

{% include "includes/sidebar.html" %}

  <div class="row">
    <header>
      <div class="page-header min-height-300">
        <span class="mask bg-gradient-primary opacity-6"></span>
      </div>
    </header>

    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
      <section class="py-sm-7 py-5 position-relative">
        <div class="container">
          <div class="row">
            <div class="col-12 mx-auto">
              <div style="float: right" class="mt-n6">
                {% include "includes/search_form.html" %}
              </div>
              <br><br>
              <div class="col-lg-9 col-md-9 z-index-2 position-relative px-md-1 px-sm-5 mx-auto mb-2">
                <br>
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <h2 class="mb-2">Positions</h2>
                </div>
                {% if position_list %}
                  <p class="mb-6">Find out about duties in your team!</p>
                {% else %}
                  <p class="mb-6">No existing positions!</p>
                {% endif %}
                {% for position in position_list %}
                  <div class="mb-5">
                    <div class="d-flex justify-content-between align-items-center mb-2">
                      <h5 class="mb-3"><i>{{ position.name }}</i></h5>
                    </div>
                    <ul class="list-unstyled">
                      {% for duty in position.duties_to_a_list %}
                        <li class="list-item mb-1">
                          {{ duty }}
                        </li>
                      {% endfor %}
                    </ul>
                  </div>
                  <hr class="hr mb-5">
                {% endfor %}
                {% include 'includes/pagination.html' %}
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>

{% endblock content %}

templates/workflow_organizer/project_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ project.name }} {% endblock %}

{% block content %}

{% include "includes/sidebar.html" %}

  <div class="row">
    <header>
{#      Filler#}
    </header>

    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
      <section class="py-sm-7 py-5 position-relative">
        <div class="container mt-10">
          <div class="row">
            <div class="col-12 mx-auto">
              <div class="col-lg-9 col-md-9 z-index-2 position-relative px-md-1 px-sm-5 mx-auto mb-2">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <h3 class="mb-2">{{ project.name }}</h3>
                  {% if user.is_authenticated %}
                    <div class="dropdown">
                      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown button
                      </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <a class="dropdown-item py-2 ps-3 border-radius-md" target="_blank" href="{% url 'workflow_organizer:project-update' pk=project.id %}">
                            <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-center align-items-center p-0">Edit project</h6>
                          </a>
                          <a class="dropdown-item py-2 ps-3 border-radius-md" target="_blank" href="{% url 'workflow_organizer:project-delete' pk=project.id %}">
                            <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-center align-items-center p-0">Delete project</h6>
                          </a>
                        </div>
                       </div>
                      </div>
                    </div>
                  {% endif %}
                </div>
                  <table class="mx-n2 table table-borderless">
                    <thead>
                      <tr>
                        <td></td>
                        <td></td>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td class="text-muted"><i>Completion</i></td>
                        <td>
                          <div class="progress-wrapper">
                            <div class="progress-info">
                              <div class="progress-percentage">
                                <span class="text-xs text-muted font-weight-bold">{{ project.progress }}%</span>
                              </div>
                            </div>
                            <div style="width: 180px;" class="progress">
                              <div class="progress-bar bg-gradient-info w-{{ project.progress }}" role="progressbar" aria-valuenow="{{ project.progress }}" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                          </div>
                        </td>
                      </tr>
                      <tr>
                        <td class="text-muted"><i>Budget</i></td>
                        <td style="font-size: 13px" class="font-weight-bolder text-muted">{{ project.budget }}$</td>
                      </tr>
                      <tr>
                        <td class="text-muted"><i>Team</i></td>
                        <td>
                          {% if project.team %}
                          <div class="avatar-group">
                            <a href="{% url 'workflow_organizer:team-detail' pk=project.team.id %}" class="avatar ms-3 avatar-sm rounded-circle" data-bs-toggle="tooltip" data-bs-placement="bottom" title="{{ project.team.name }}">
                              <p style="display: inline" class="text-muted mt-3 me-0">{{ project.team.name }}</p>
                            </a>
                            {% else %}
                            <a href="{% url 'workflow_organizer:toggle-project-assign' pk=project.id %}"
                               class="btn mt-n2 py-1 px-3 text-muted"
                               style="box-shadow: 0 0.3125rem 0.625rem 0 rgba(51, 153, 255, 0.32)">
                              <i class="text-xs">Assign my team</i>
                            </a>
                          </div>
                          {% endif %}
                            {% if project in user.team.projects.all %}
                              <a href="{% url 'workflow_organizer:toggle-project-assign' pk=project.id %}"
                                 class="btn mt-n2 py-1 px-3 ms-5 text-muted"
                                 style="box-shadow: 0 0.3125rem 0.625rem 0 rgba(51, 153, 255, 0.32)">
                                <i class="text-xs">Eliminate my team</i>
                              </a>
                            {% endif %}
                        </td>
                      </tr>
                      <tr>
                        <td class="text-muted"><i>Crunch time</i></td>
                        <td>
                          {{ project.time_constraints }}
                        </td>
                      </tr>
                    </tbody>
                  </table>
                  <hr class="hr mb-4" style="border-bottom: 1px solid rgba(0, 0, 0, .5)">
                  <div class="row mb-4">
                    <h5 class="h5 mb-4 mt-2">Depiction</h5>
                    <p>{{ project.depiction }}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>

{% endblock content %}

templates/workflow_organizer/project_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} {{ object|yesno:"Edit,Create" }} Project {% endblock %}

{% block content %}
{% include "includes/sidebar.html" %}

  <div class="row">
    <header>
      <div class="page-header min-height-300">
        <span class="mask bg-gradient-success opacity-4"></span>
      </div>
    </header>

    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
      <section class="py-sm-7 py-5 position-relative">
        <div class="container">
          <div class="row">
            <div class="col-12 mx-auto">
              <div class="col-lg-9 col-md-9 z-index-2 position-relative px-md-1 px-sm-5 mx-auto mb-2">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <h3 class="mb-2 mx-auto">{{ object|yesno:"Edit,Create" }} Project </h3>
                </div>
                <br><br>
                <form role="form" method="post" action="">
                  {% csrf_token %}
                  <div class="form-group row">
                    <div class="col">
                      {{ form.name|as_crispy_field }}
                    </div>
                    <div class="col">
                      {{ form.is_completed|as_crispy_field }}
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col mt-2">
                      {{ form.budget|as_crispy_field }}
                    </div>
                    <div class="col mt-n4">
                      {{ form.team|as_crispy_field }}
                    </div>
                    <div class="col mt-n4">
                      {{ form.progress|as_crispy_field }}
                    </div>
                  </div>
                  {{ form.depiction|as_crispy_field }}
                  {{ form.time_constraints|as_crispy_field }}
                  <div class="text-center">
                    <input type="submit" class="btn btn-lg bg-gradient-dark mt-4 mb-0" value="Submit">
                    <a href="{% url 'workflow_organizer:dashboard' %}" class="btn bg-gradient-secondary btn-lg mt-4 mb-0 mx-3">Cancel</a>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>

{% endblock content %}

templates/workflow_organizer/task_type_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} Managing of tasks {% endblock %}

{% block content %}

{% include "includes/sidebar.html" %}

  <div class="row">
    <header>
      <div class="page-header min-height-300">
        <span class="mask bg-gradient-info opacity-6"></span>
      </div>
    </header>
    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
      <section class="py-sm-7 py-5 position-relative">
        <div class="container">
          <div class="row">
            <div class="col-12 mx-auto">
              <div style="float: right" class="mt-n6">
                {% include "includes/search_form.html" %}
              </div>
              <br><br>
              <div class="row py-5">
                <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mx-auto mb-4">
                  <div class="d-flex justify-content-between align-items-center">
                    <h2 class="mb-4">Task Types</h2>
                    <div class="row">
                      <a style="width: 40px; height: 40px; box-shadow: 0 0.3125rem 0.625rem 0 rgba(51, 153, 255, 0.32)" href="{% url 'workflow_organizer:task-type-create' %}" class="btn btn-white mx-3">
{#                      filler#}
                      </a>
                    </div>
                  </div>
                  <br>
                  {% if task_type_list %}
                    {% for task_type in task_type_list %}
                      <div style="width:100%; box-shadow: 0 0.3125rem 0.625rem 0 rgba(51, 153, 255, 0.32)" class="card mb-3">
                        <div class="card-body">
                          <div class="d-flex justify-content-between align-items-center">
                            <div class="card-title"><h5><i>#{{ task_type.name }}</i></h5></div>
                            <div class="row">
                              <a style="width: 40px; height: 40px; box-shadow: 0 0.3125rem 0.625rem 0 rgba(51, 153, 255, 0.32)" href="{% url 'workflow_organizer:task-type-update' pk=task_type.id %}" class="btn btn-white mx-3">
{#                              filler#}
                              </a>
                              <a style="width: 40px; height: 40px; box-shadow: 0 0.3125rem 0.625rem 0 rgba(51, 153, 255, 0.32)" href="{% url 'workflow_organizer:task-type-delete' pk=task_type.id %}" class="btn btn-white mx-3">
{#                              filler#}
                              </a>
                            </div>
                          </div>
                          <div class="card-text"><p class="text-sm">{{ task_type.depiction }}</p></div>
                        </div>
                      </div>
                    {% endfor %}
                  {% else %}
                    <p>There are no task types yet!</p>
                  {% endif %}
                  {% include 'includes/pagination.html' %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>

{% endblock content %}